export interface Cajainstitucional{
    numeroTgr: string,
    institucionId: number,
    tipoDocumento: number,
    numeroDocumento: string,
    nombreCiudadano: string,
    totalPagarTgr: number,
    fechaGeneracionTgr: string,
    fechaVencimientoTgr: string,
    origenCreacion: string,
    estadoTgr: string,
    canalPago: any,
    servicios: string,
    origenPago: any,
    nombreCaja: string,
}